<a href="https://colab.research.google.com/github/DevaHarshiniModepalli/DevaHarshini425/blob/main/devaharshini425_tillnumpy(21/1)nb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# day 4
s1={21,54,46,89}
s1.add(24)
print(s1)

{46, 21, 54, 24, 89}


In [ ]:
s2={76,7,46}
s1.union(s2)

{7, 21, 24, 46, 54, 76, 89}

In [ ]:
s1.difference(s2)

{21, 24, 54, 89}

In [ ]:
s2.difference(s1)

{7, 76}

In [ ]:
s1.symmetric_difference(s2)

{7, 21, 24, 54, 76, 89}

In [ ]:
a=(3,5,7)
l=list(a)
l.append(9)
print(tuple(l))

(3, 5, 7, 9)


In [ ]:
s={10,20}
l=list(s)
l.insert(1,45)
print(set(l))

{10, 20, 45}


In [ ]:
t=(1,3,2)
t.index(3)

1

In [ ]:
t.count(2)

1

In [ ]:
#sum of n positive numbers
n=int(input( ))
def sumofpnum(n):
  sum=0
  for i in range(1,n+1):
    sum=sum+i
  print(sum)
sumofpnum(n)


4
10


In [ ]:
# day 5
d={1:6,6:647,45:6}
d.get(1)
# d.update({6:657})


6

In [ ]:
d = {1: 6, 6: 647, 45: 6}
del d[6]
print(d)

{1: 6, 45: 6}


In [ ]:
d[1]=[658,73]
d

{1: [658, 73], 45: 6}

In [ ]:
d[1][0]

658

In [ ]:
d[1]=[5,34.6,'a','xyz']
d[2]=(25,467,780)
d[3]=9864
d['apple']=(20,10,70,[90,180,270])
d

{1: [5, 34.6, 'a', 'xyz'],
 45: 6,
 2: (25, 467, 780),
 3: 9864,
 'apple': (20, 10, 70, [90, 180, 270])}

In [ ]:
type(d[1][1])

int

In [ ]:
d['apple'][3][0]

90

In [ ]:
d={102:{50:[7,8,9,10],'apple':(20,10,70,[90,180,270])}}
d

{102: {50: [7, 8, 9, 10], 'apple': (20, 10, 70, [90, 180, 270])}}

In [ ]:
d[102]['apple'][3][0]

90

In [ ]:
# day 5 assignment
# function to calculate the square of a number
def calculate_square(n):
    return n * n
user_input = int(input("Enter a positive integer to find its square: "))
square_result = calculate_square(user_input)
print("The square of", user_input, "is:", square_result)


Enter a positive integer to find its square: 4
The square of 4 is: 16


In [ ]:


n = int(input("Enter a positive integer: "))

# Using a for loop to print all numbers from 1 to n
print("Numbers from 1 to", n, ":")
for i in range(1, n+1):
    print(i)

# Using a while loop to calculate the sum of all numbers from 1 to n
sum_numbers = 0
i = 1
while i <= n:
    sum_numbers += i
    i += 1

print("Sum of all numbers from 1 to", n, "is:", sum_numbers)


Enter a positive integer: 5
Numbers from 1 to 5 :
1
2
3
4
5
Sum of all numbers from 1 to 5 is: 15


In [ ]:
# day 6
# control statements
x=6
if x%2==0:
  print("Even")
else:
  print("Odd")


Even


In [ ]:
a='india3536'
a

'india3536'

In [ ]:
a.isalpha()

False

In [ ]:
name='india'
if name.isalpha()==True:
  print("Accept")
else:
  print("Name can't contain numbers")

Accept


In [ ]:
 name.lower()
 bool(name.lower())

True

In [ ]:
bool( " ")

True

In [ ]:
bool("  797  6")

True

In [ ]:
# basic function for one time use
x=input("Enter a string: ")
if(x[0]=="m" or x[0]== "M"):
  print("Yes")
else:
  print("No")

Enter a string: delhi
No


In [ ]:
# function
def char_check(x):
  if(x[0]=="m" or x[0]== "M"):
    print("Yes")
  else:
    print("No")
char_check(input("Enter a string: "))


Enter a string: maharastra
Yes


In [ ]:
x=input("Enter a string: ")
if x.startswith("m") or x.startswith("M"):
  print("Yes")
else:
  print("No")

Enter a string: manipur
Yes


In [ ]:
# faster and lesser code
x='megha'
if x[0].lower()=='m':
  print("Yes")
else:
  print("No")

Yes


In [ ]:
# m,s,h
x='singapore'
if x[0].lower()=='m' or x[0].lower()=='s' or x[0].lower()=='h':
  print("Yes")
else:
  print("No")

Yes


In [ ]:
x='india'
r=['m','s','h','g','t']
if x[0].lower() in r:
  print("Yes")
else:
  print("No")

No


In [ ]:
if x[0].lower() in ('s','h','g','t','m'):
  print("Yes")
else:
  print("No")

No


In [ ]:
# day7 notebook
x=35
while x>10:
  print("YES",x)
  # x=x-5 decrement

YES 35
YES 30
YES 25
YES 20
YES 15


In [ ]:
# for loop used 6o access the elemnts of iterables in non iterables
y=[40,20,80,50,30,60,90]
for i in range(len(y)):
  y[i]+=5
  i+=1
print(y)


[45, 25, 85, 55, 35, 65, 95]


In [ ]:
for i in range(len(y)):
  y[i]=(y[i]*y[i]*3.14)
  i+=1
print(y)

[6358.5, 1962.5, 22686.5, 9498.5, 3846.5, 13266.5, 28338.5]


In [ ]:
lr=[]  # sum=0
for i in y:
  # print(i*i*3.14) #sum+=y[i]
  lr.append(i*i*3.14)
print(lr)


[126951839.86500001, 12093415.625, 1616086666.265, 283295517.065, 46458065.465, 552640069.865, 2521641628.265]


In [ ]:
num=[39,45,66,93,90,78,67,87,89,93,24,59,49,91]
len(num)
a=[];b=[]
for i in num:
  if i%2==0:
    a.append(i)
  else:
    b.append(i)
print("Even: ",a)
print("Odd: ",b)

Even:  [66, 90, 78, 24]
Odd:  [39, 45, 93, 67, 87, 89, 93, 59, 49, 91]


In [ ]:
a=86
type(a)

int

In [ ]:
b='hgdutd' # b initialised with a string
b=6865.65468 # with float
type(b)
b=[] # with a list


In [ ]:
#day 8 note book
def calcArea(r):
  area=3.14*r*r
  return area # if used "print(x)",type becomes "nonetype"
calcArea(10)

314.0

In [ ]:
def d_to_inr(x):
  return(x*85) # if used "print" func, you can't take the sum or avg when getting collective analysis
d_to_inr(15)

1275

In [ ]:
def d_to_inr(x):
  print(x*85) # throws error as print returns the type as none type. since no operations performed on none type of data
a=d_to_inr(45)
b=d_to_inr(67)
a+b

3825
5695


TypeError: unsupported operand type(s) for +: 'NoneType' and 'NoneType'

In [ ]:
def d_to_inr(x):
  return(x*85)
a=d_to_inr(45)
b=d_to_inr(67)
a+b

9520

In [ ]:
def area(l,w):
  r=l*w
  return r
area(4,6)

24

In [ ]:
area(w=6,l=4)

24

In [ ]:
def area(rad,length,width):
  aoc=3.14*rad*rad
  aor=length*width
  return {"Area of rectangle":aor,"Area of circle":aoc}
# area()

In [ ]:
aor,aoc=area(rad=5,length=10,width=20)
# aor
aoc

78.5

In [ ]:
s=area(rad=5,length=10,width=20)
s

{'Area of rectangle': 200, 'Area of circle': 78.5}

In [ ]:
s[0] #resulatant output from area function is a set which is not indexed

TypeError: 'set' object is not subscriptable

In [ ]:
type(s)

dict

In [ ]:
s["Area of rectangle"]


200

In [ ]:
def count(t):
  alpha=0
  digit=0
  for i in t:
    if i.isalpha(): # is.alpha() is an inbuilt method of python library
      alpha+=1
    if i.isdigit(): # is.digit() is an inbuilt method of python library
      digit+=1
  return alpha,digit

In [ ]:
count('HyderabAAd  500008 Telangana')

(19, 6)

In [ ]:
def nonum(t):
  r1=''
  for i in t:
    if i.lower().isalpha() or i==' ':
      r1+=i
  return r1


In [ ]:
nonum('HyderabAAd  500008 Telangana')

'HyderabAAd   Telangana'

In [ ]:
def nonum(t):
  r1=''
  for i in t:
    # if i.lower().isalpha() or i==' ':
    if i.isdigit()==False:
      r1+=i
  return r1


In [ ]:
nonum("ytfywetfuwe 9876 ")

'ytfywetfuwe  '

1.numpy
2.pandas
3.matplotlib and seaborn
4.sklearn
5.statsmodels
6.scipy

In [ ]:
#day-(17/1/25)
import numpy as np
j=[5,7,4,6,9,8]
d=np.array(j)

In [ ]:
type(j)

list

In [ ]:
type(d)

numpy.ndarray

In [ ]:
d.shape # shape is a method used to get shape-dimension "(order)", only used in array-numpy!

(6,)

In [ ]:
j.shape #error caz, j is a list but not an array of numpy!

AttributeError: 'list' object has no attribute 'shape'

In [ ]:
d.ndim# gives dimension n=" "

1

In [ ]:
j.ndim #doesnt work on a list

AttributeError: 'list' object has no attribute 'ndim'

In [ ]:
d.size

6

In [ ]:
j.size

AttributeError: 'list' object has no attribute 'size'

In [ ]:
s=[[4,8,90,12],[56,78,54,20],[67,89,50,49],[77,88,22,55],[90,40,70,60]]

In [ ]:
arr=np.array(s)


In [ ]:
arr.shape
# arr.size

(5, 4)

In [ ]:
arr.size

20

In [ ]:
arr.reshape(5,2)

ValueError: cannot reshape array of size 20 into shape (5,2)

In [ ]:
arr.reshape(4,5)

array([[ 4,  8, 90, 12, 56],
       [78, 54, 20, 67, 89],
       [50, 49, 77, 88, 22],
       [55, 90, 40, 70, 60]])

In [ ]:
a1=arr.reshape(2,2,5)
a1

array([[[ 4,  8, 90, 12, 56],
        [78, 54, 20, 67, 89]],

       [[50, 49, 77, 88, 22],
        [55, 90, 40, 70, 60]]])

In [ ]:
a1.shape


(2, 2, 5)

In [ ]:
a1.reshape(20)

array([ 4,  8, 90, 12, 56, 78, 54, 20, 67, 89, 50, 49, 77, 88, 22, 55, 90,
       40, 70, 60])

In [ ]:
a1.shape

(2, 2, 5)

In [ ]:
a1.reshape(20,1)

array([[ 4],
       [ 8],
       [90],
       [12],
       [56],
       [78],
       [54],
       [20],
       [67],
       [89],
       [50],
       [49],
       [77],
       [88],
       [22],
       [55],
       [90],
       [40],
       [70],
       [60]])

In [ ]:
a1.ndim

3

In [ ]:
range(5,20)

range(5, 20)

In [ ]:
m=[1,2,3,4,5]
y=range(1,6,2)# stepsize is 2 here
m1=list(y)
m1

[1, 3, 5]

In [ ]:
tuple(range(-10,1))

(-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0)

very very important to reemember the **negative step size** in case of reverse traversal


In [ ]:
tuple(range(0,-10,-1))

(0, -1, -2, -3, -4, -5, -6, -7, -8, -9)

In [ ]:
tuple(range(-1,-10,-1))# going from -ve to +ve ,so use -ve stepsize!


(-1, -2, -3, -4, -5, -6, -7, -8, -9)

In [ ]:
b=np.arange(2.5,5.0,0.5)# arange method of numpy , simply makes an array of these range and displays array by default if not converted
tuple(b)


(2.5, 3.0, 3.5, 4.0, 4.5)

In [ ]:
np.arange(2.5,5.0,0.5) # as said above!

array([2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
even=[]
odd=[]
for i in j:
  if(j.index(i)%2==0):
    even.append(i)
  else:
    odd.append(i)
print(even)
print(odd)

[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]


In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
j.index(80)

6

In [ ]:
j=[5,87,23,46,62,84,80,45,77,33,80]
even=[]
odd=[]
for i in range(len(j)):
  if(i%2==0):
    even.append(j[i])
  else:
    odd.append(j[i])
print(even)
print(odd)

[5, 23, 62, 80, 77, 80]
[87, 46, 84, 45, 33]


In [ ]:
np.mean(d)

6.5

In [ ]:
np.median(d)

6.5

In [ ]:
np.var(d)

2.9166666666666665

In [ ]:
np.std(d)# std=(var)^1/2

1.707825127659933

In [ ]:
np.min(d)

4

In [ ]:
np.max(d)

9

In [ ]:
Q1=np.quantile(d,0.25)
Q2=np.quantile(d,0.50)
Q3=np.quantile(d,0.75)
print(f"Q1:{Q1}\nQ2:{Q2}\nQ3:{Q3}\n")

Q1:5.25
Q2:6.5
Q3:7.75



DISTRIBUTIONS:
Normal,
Binomial,
Poison,
uniform :values are in [0,1)

In [ ]:
r=np.random.rand(3,5,2) # to create data that follows uniform dist, range[0,1)!
r

array([[[0.51781837, 0.62305009],
        [0.02598839, 0.08388954],
        [0.21180127, 0.22699386],
        [0.04616855, 0.62961928],
        [0.86863299, 0.85669558]],

       [[0.74320141, 0.0676402 ],
        [0.03460574, 0.09619159],
        [0.1228908 , 0.91646587],
        [0.85081738, 0.69693838],
        [0.34898675, 0.46919005]],

       [[0.97314319, 0.61177885],
        [0.62193857, 0.61422734],
        [0.73473787, 0.14642583],
        [0.42257431, 0.09334739],
        [0.67622825, 0.30912166]]])

In [ ]:
r.shape

(3, 5, 2)

In [ ]:
r.size

30

In [ ]:
r.ndim

3

In [ ]:
sd=np.random.randn(4,10) #-3 to +3 : range for std normal dist!
sd

array([[ 0.43211119,  0.04499294,  0.79600265, -2.28534538, -0.69151535,
         0.47604764, -0.42661144, -1.07730165,  0.47030699, -1.64495695],
       [-0.66454273, -0.88159631,  0.45153915, -1.05844685,  0.1948814 ,
        -0.78521974, -1.09337067,  0.0327815 ,  0.02483654, -0.55081857],
       [-0.43653408,  1.02225997,  0.74266009,  0.25144325, -1.59369113,
         0.03193158,  1.43061608, -0.62892144,  1.79478885,  1.37504822],
       [-1.95564144, -0.62052344, -1.44480982, -0.06674011,  1.5854289 ,
         0.06083007, -1.06124709, -0.80852562,  0.77632412,  0.30336438]])

In [ ]:
sd.shape

(4, 10)

In [ ]:
sd.ndim

2

In [ ]:
np.random.normal(40,5,(4,8)) #in this form as(4,8)

array([[46.24028293, 31.59781174, 38.3584632 , 42.74815615, 33.94810073,
        44.32880989, 37.03267248, 39.17255347],
       [50.09495578, 47.30480381, 40.67320007, 44.59858756, 37.25250795,
        33.09478709, 49.07320185, 30.25751811],
       [46.28112325, 44.14567919, 36.91894473, 39.46186309, 42.84025412,
        40.5087748 , 35.98281581, 42.89445893],
       [35.10100489, 46.04577242, 37.00716128, 43.37270397, 45.15358033,
        44.21169617, 41.28609442, 39.02363862]])

In [ ]:
np.random.randint(10,50,5)

array([31, 43, 29, 15, 11])

In [ ]:
#day 2
h=[30,20,5,8,9]
h


[30, 20, 5, 8, 9]

In [ ]:
k=[]
for i in (h):
  # i=i+7
  k.append(i+7)
print(k)

[37, 27, 12, 15, 16]


In [ ]:
s=(6,2,3,9,7,5,8)
s

(6, 2, 3, 9, 7, 5, 8)

In [ ]:
r=[]
s1=list(s)
for i in s:
  r.append(i**2)
r1=tuple(r)
r1

(36, 4, 9, 81, 49, 25, 64)

In [ ]:
tuple(i**2 for i in s)

(36, 4, 9, 81, 49, 25, 64)

In [ ]:
for i in r:
  if i>50:
    print(i)

81
64


In [ ]:
tuple(i for i in r if i>50)

(81, 64)

In [ ]:
list(i for i in r if i>50)

[81, 64]

In [ ]:
import numpy as np
arr=np.array([20,50,30,70,80,40,36,54,23,98])
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

declaring an array using **np.array** is **mandatory** to make it array of **numpy**


In [ ]:
arr+7

array([ 27,  57,  37,  77,  87,  47,  43,  61,  30, 105])

need to use for loop for accesing and operating elements of list or tuple but in arrays of numpy, no need to use **for** loop , but **just** the **operator**


In [ ]:
arr

array([20, 50, 30, 70, 80, 40, 36, 54, 23, 98])

array operations in numpy are **temporary**.if you print arr back, **original** one is printed. if needed to **change**, assign the array to a  **new** variable


In [ ]:
arr%4

array([0, 2, 2, 2, 0, 0, 0, 2, 3, 2])

In [ ]:
arr>50

array([False, False, False,  True,  True, False, False,  True, False,
        True])

In [ ]:
arr[4:8:2]

array([80, 36])

In [ ]:
k=[36,4,9,81,49,25,64]
for i in range(len(k)):
  if k[i]>50:
    print(i)

3
6


In [ ]:
list(i for i in range(len(k)) if k[i]>50)

[3, 6]

**faster** way of writing same code as above in just **one** line

In [ ]:
arr[arr>50]

array([70, 80, 54, 98])

In [ ]:
np.where(arr>50)

(array([3, 4, 7, 9]),)

In [ ]:
import numpy as np

# Generate a 7x7 array with random values between 0 and 1
a = np.random.rand(7, 7)

# Print the array
print(a)

[[0.18353581 0.54182334 0.69016492 0.13191315 0.97168736 0.13770766
  0.09641529]
 [0.90472284 0.17335685 0.5257982  0.17266659 0.37932854 0.11123418
  0.96642777]
 [0.85108664 0.46110419 0.70278107 0.35103272 0.19817228 0.5772982
  0.09348457]
 [0.35405868 0.76369466 0.50190921 0.36273863 0.27609046 0.67453936
  0.03272796]
 [0.20577844 0.05344589 0.44252294 0.53355731 0.71159464 0.13959689
  0.19674685]
 [0.50677762 0.08755774 0.791507   0.75383765 0.27285596 0.59950299
  0.82707959]
 [0.16980546 0.50029172 0.41344148 0.01506597 0.27538384 0.57650478
  0.07977895]]


In [ ]:
import numpy as np

# Generate a 7x7 array with random double-digit integers between 10 and 99 (inclusive)
a = np.random.randint(10, 100, size=(7, 7))

# Print the array
print(a)

[[53 56 17 39 59 73 41]
 [32 44 77 15 44 15 73]
 [81 22 68 38 15 42 28]
 [42 73 51 54 22 43 30]
 [79 50 15 14 63 75 56]
 [78 62 37 90 11 71 91]
 [90 56 99 18 40 40 18]]


In [ ]:
a[:,6]

array([41, 73, 28, 30, 56, 91, 18])

In [ ]:
a[:,-1]

array([41, 73, 28, 30, 56, 91, 18])

In [ ]:
a[3,2]

51

In [ ]:
a[:3]

array([[53, 56, 17, 39, 59, 73, 41],
       [32, 44, 77, 15, 44, 15, 73],
       [81, 22, 68, 38, 15, 42, 28]])

In [ ]:
a[2:]

array([[81, 22, 68, 38, 15, 42, 28],
       [42, 73, 51, 54, 22, 43, 30],
       [79, 50, 15, 14, 63, 75, 56],
       [78, 62, 37, 90, 11, 71, 91],
       [90, 56, 99, 18, 40, 40, 18]])

remember the **end** index is always open! meaning that **index is not considered**!

In [ ]:
a[2:7:2]

array([[81, 22, 68, 38, 15, 42, 28],
       [79, 50, 15, 14, 63, 75, 56],
       [90, 56, 99, 18, 40, 40, 18]])

In [ ]:
a[2:7:2,]

array([[81, 22, 68, 38, 15, 42, 28],
       [79, 50, 15, 14, 63, 75, 56],
       [90, 56, 99, 18, 40, 40, 18]])

In [ ]:
a[2:7:2,1:5]

array([[22, 68, 38, 15],
       [50, 15, 14, 63],
       [56, 99, 18, 40]])

In [ ]:
a[2:5,2:6]

array([[68, 38, 15, 42],
       [51, 54, 22, 43],
       [15, 14, 63, 75]])

In [ ]:
a[2:5:2,2:6]

array([[68, 38, 15, 42],
       [15, 14, 63, 75]])

In [ ]:
a[2:5,2:6:3]

array([[68, 42],
       [51, 43],
       [15, 75]])

In [1]:
import pandas as pd
import seaborn as sns


In [2]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [3]:
k=[5,6,2,9,7,40,20,45]
k

[5, 6, 2, 9, 7, 40, 20, 45]

numpy has **n dimensional objects**. but in pandas, there are only only **tabular** form or say **one dimension and two dimensional  objects only**!

In [4]:
pd.Series(k)

0     5
1     6
2     2
3     9
4     7
5    40
6    20
7    45
dtype: int64

In [9]:
import numpy as np
a=np.random.randint(20,50,(5,4))
a

array([[45, 49, 38, 48],
       [27, 29, 32, 23],
       [27, 25, 46, 31],
       [48, 20, 36, 42],
       [49, 26, 49, 30]])

while generating data using numpy library, we can directly mention the **order of the array in the 3rd parameter** of function!

In [10]:
a.ndim

2

In [11]:
pd.DataFrame(a)


0   1   2   3
0  45  49  38  48
1  27  29  32  23
2  27  25  46  31
3  48  20  36  42
4  49  26  49  30

In [27]:
df1=pd.DataFrame(a,columns=['roll no','age','marks','height'],index=[392,425,419,378,245])
df1

roll no  age  marks  height
392       45   49     38      48
425       27   29     32      23
419       27   25     46      31
378       48   20     36      42
245       49   26     49      30

In [14]:
df=sns.load_dataset('iris')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
type(df)

pandas.core.frame.DataFrame

if the object type is a **dataframe**,
 you can use **shape, column **mehtods


In [20]:
df.shape #gives row, col
# df.shape[1] gives you only column
# df.shape[0] gives you only row

5

In [22]:
# df.columns
df.columns[-1]

'species'

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


first col is **shape,** column name, and so on

In [32]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [30]:
df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

Missing values are denoted by '**nan**' in pandas

In [31]:
46-(34+24)

-12

In [33]:
df['sepal_length'].mean()

5.843333333333334

on **column**, we can use these methods of cetntral tendencies.

In [35]:
df['sepal_length'].median()

5.8

In [36]:
df['sepal_length'].mode()

0    5.0
Name: sepal_length, dtype: float64

In [37]:
df['sepal_length'].var()

0.6856935123042505

In [38]:
df['sepal_length'].std()

0.8280661279778629